load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("scm_client_infra")

python_library(
    name = "lib",
    srcs = glob(["*.py"]),
    typing = True,
    deps = [
        "//eden/integration/lib:lib",
        "//watchman/python/pywatchman:pywatchman",
    ],
)
