defaults: &defaults
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: Install dependencies
        command: apt-get update && apt-get install cmake libtool m4 automake npm -y
    - run:
        environment:
          USE_CMAKE: 1
        command: ./travis/run.sh
    - run:
        environment:
          USE_CMAKE: 0
        command: ./travis/run.sh

version: 2
jobs:
  build-python27:
    <<: *defaults
    docker:
      - image: python:2.7
  build-python36:
    <<: *defaults
    docker:
      - image: python:3.6

workflows:
  version: 2
  build:
    jobs:
      - build-python27
      - build-python36
