defaults: &defaults
  working_directory: ~/repo
  steps:
    - run:
        name: Install dependencies
        command: |
          apt-get update
          apt-get install -yq ccache libtool m4 python openssh-client git autoconf-archive bison build-essential curl flex git gperf joe libboost-all-dev libcap-dev libdouble-conversion-dev libevent-dev libgflags-dev libgoogle-glog-dev libkrb5-dev libpcre3-dev libnuma-dev libsasl2-dev libsnappy-dev libsqlite3-dev libssl-dev libtool netcat-openbsd pkg-config sudo unzip wget libpthread-stubs0-dev libidn11
    - restore_cache:
        keys:
          - build-linux-debug-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
        paths:
          - ~/.ccache
    - checkout
    - run:
        name: Python version
        command: python -V && env
    - run:
        name: Run build
        no_output_timeout: 86400
        command: |
          export CCACHE_DIR=$HOME/.ccache
          mkdir -p $CCACHE_DIR
          GETDEPS="build/fbcode_builder/getdeps.py"
          "$GETDEPS" build watchman
          "$GETDEPS" test watchman
          inst_dir=$("$GETDEPS" show-inst-dir watchman)
          src_dir=$("$GETDEPS" show-source-dir watchman)
          python "${src_dir}/runtests.py" \
            --pybuild-dir="${inst_dir}/../../build/watchman/python/build" \
            --watchman-path="${inst_dir}/bin/watchman"
    - save_cache:
        key: build-linux-debug-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
        paths:
          - ~/.ccache
        when: always

version: 2
jobs:
  build-python27:
    <<: *defaults
    docker:
      - image: python:2.7-stretch
  build-python36:
    <<: *defaults
    docker:
      - image: python:3.6-stretch
  ubuntu-18.04:
    <<: *defaults
    docker:
      - image: ubuntu:18.04
  mac:
    macos:
      xcode: 10.2.1
    steps:
      - checkout
      - run:
          name: Python version
          command: python -V && env
      - run:
          name: Run build
          no_output_timeout: 86400
          command: |
            GETDEPS="build/fbcode_builder/getdeps.py"
            "$GETDEPS" build watchman
            "$GETDEPS" test watchman
            inst_dir=$("$GETDEPS" show-inst-dir watchman)
            src_dir=$("$GETDEPS" show-source-dir watchman)
            python "${src_dir}/runtests.py" \
              --pybuild-dir="${inst_dir}/../../build/watchman/python/build" \
              --watchman-path="${inst_dir}/bin/watchman"


workflows:
  version: 2
  build:
    jobs:
      #- build-python27
      #- build-python36
      - ubuntu-18.04
      - mac
