defaults: &defaults
  working_directory: ~/repo
  steps:
    - run:
        name: Install dependencies
        command: |
          apt-get update
          apt-get install -yq ccache libtool m4 python openssh-client git autoconf-archive bison build-essential curl flex git gperf joe libboost-all-dev libcap-dev libdouble-conversion-dev libevent-dev libgflags-dev libgoogle-glog-dev libkrb5-dev libpcre3-dev libnuma-dev libsasl2-dev libsnappy-dev libsqlite3-dev libssl-dev libtool netcat-openbsd pkg-config sudo unzip wget libpthread-stubs0-dev libidn11
    - restore_cache:
        keys:
          - build-linux-debug-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
        paths:
          - ~/.ccache
          - ~/cmake-3.6.2-Linux-x86_64
    - run:
        name: Get newer cmake
        command: |
            if [ ! -d ~/cmake-3.6.2-Linux-x86_64 ]; then
              echo "No cache - building CMake"
              cd ~
              # Note that this requires libidn.so.11
              wget --quiet https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz
              tar -xvf cmake-3.6.2-Linux-x86_64.tar.gz
            else
              echo "Cached CMake found"
            fi
    - checkout
    - run:
        name: Run getdeps.py
        command: python ./getdeps.py --install-deps -j2
    - run:
        name: Python version
        command: python -V && env
    - run:
        name: Run build
        command: |
          export PATH=$HOME/cmake-3.6.2-Linux-x86_64/bin:$PATH
          export CCACHE_DIR=$HOME/.ccache
          mkdir -p $CCACHE_DIR
          cmake .
          make VERBOSE=1 -j2
          make integration VERBOSE=1 -j2
    - save_cache:
        key: build-linux-debug-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
        paths:
          - ~/.ccache
          - ~/cmake-3.6.2-Linux-x86_64
        when: always

version: 2
jobs:
  build-python27:
    <<: *defaults
    docker:
      - image: python:2.7-stretch
  build-python36:
    <<: *defaults
    docker:
      - image: python:3.6-stretch
  ubuntu-18.04:
    <<: *defaults
    docker:
      - image: ubuntu:18.04

workflows:
  version: 2
  build:
    jobs:
      #- build-python27
      #- build-python36
      - ubuntu-18.04
