defaults: &defaults
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: Install dependencies
        command: apt-get update && apt-get install sudo python build-essential nodejs cmake libtool m4 automake -y
    - run:
        name: Run getdeps.py
        command: python ./getdeps.py --install-deps -j2
    - run:
        name: Python version
        command: python -V && env
    - run:
        name: Build and test
        command: ./travis/run.sh

version: 2
jobs:
  build-python27:
    <<: *defaults
    docker:
      - image: python:2.7-stretch
  build-python36:
    <<: *defaults
    docker:
      - image: python:3.6-stretch
  ubuntu-18.04:
    <<: *defaults
    docker:
      - image: ubuntu:18.04
  mac-python26:
    macos:
      xcode: "9.0"
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install deps
          command: TRAVIS_PYTHON=python2.6 ./travis/deps.sh
      - run:
          name: Buid and test
          command: TRAVIS_PYTHON=python2.6 PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig ./travis/run.sh


workflows:
  version: 2
  build:
    jobs:
      - build-python27
      - build-python36
      - ubuntu-18.04
#      - mac-python26
