load("@fbsource//tools/build_defs:rust_binary.bzl", "rust_binary")

oncall("scm_client_infra")

rust_binary(
    name = "cli",
    srcs = glob(["src/**/*.rs"]),
    autocargo = {
        "cargo_target_config": {
            "name": "watchmanctl",
        },
        "cargo_toml_config": {
            "extra_buck_dependencies": {
                "dependencies": [
                    "//watchman/rust/watchman_client:watchman_client",
                ],
            },
            "package": {
                "authors": ["Source Control Oncall oncall+source_control@xmail.facebook.com"],
                "name": "watchmanctl",
            },
        },
    },
    features = [
        "fb",
    ],
    deps = [
        "fbsource//third-party/rust:ahash",
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:duct",
        "fbsource//third-party/rust:jwalk",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:sysinfo",
        "fbsource//third-party/rust:tabular",
        "fbsource//third-party/rust:tokio",
        "//watchman/rust/watchman_client:watchman_client",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "fbsource//third-party/rust:nix",
        ],
        "ovr_config//os:macos": [
            "fbsource//third-party/rust:nix",
        ],
    }),
)
