<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'CallgrindFile' => 'lib/cov/CallgrindFile.php',
    'DwarfLineInfo' => 'lib/cov/DwarfLineInfo.php',
    'PythonProvidedWatchmanInstance' => 'lib/WatchmanInstance.php',
    'TestSkipException' => 'lib/WatchmanTestCase.php',
    'WatchmanDirectoryFixture' => 'lib/WatchmanDirectoryFixture.php',
    'WatchmanInstance' => 'lib/WatchmanInstance.php',
    'WatchmanIntegrationEngine' => 'lib/WatchmanIntegrationEngine.php',
    'WatchmanLicenseLinter' => 'lib/WatchmanLicenseLinter.php',
    'WatchmanLintEngine' => 'lib/WatchmanLintEngine.php',
    'WatchmanQueryFuture' => 'lib/WatchmanQueryFuture.php',
    'WatchmanTapEngine' => 'lib/WatchmanTapEngine.php',
    'WatchmanTestCase' => 'lib/WatchmanTestCase.php',
  ),
  'function' =>
  array(
    'execx' => 'lib/WatchmanInstance.php',
    'w_find_subdata_containing_file' => 'lib/WatchmanTestCase.php',
    'w_is_file_in_file_list' => 'lib/WatchmanTestCase.php',
    'w_is_same_file_list' => 'lib/WatchmanTestCase.php',
    'w_is_same_filename' => 'lib/WatchmanTestCase.php',
    'w_normalize_file_list' => 'lib/WatchmanTestCase.php',
    'w_normalize_filename' => 'lib/WatchmanTestCase.php',
    'w_rmdir_recursive' => 'lib/WatchmanDirectoryFixture.php',
    'w_rmdir_recursive_inner' => 'lib/WatchmanDirectoryFixture.php',
    'w_unlink' => 'lib/WatchmanTestCase.php',
  ),
  'xmap' =>
  array(
    'PythonProvidedWatchmanInstance' => 'WatchmanInstance',
    'TestSkipException' => 'Exception',
    'WatchmanIntegrationEngine' => 'WatchmanTapEngine',
    'WatchmanLicenseLinter' => 'ArcanistLinter',
    'WatchmanLintEngine' => 'ArcanistLintEngine',
    'WatchmanQueryFuture' => 'FutureProxy',
  ),
));
