<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'WatchmanInstance' => 'lib/WatchmanInstance.php',
    'WatchmanIntegrationEngine' => 'lib/WatchmanIntegrationEngine.php',
    'WatchmanLicenseLinter' => 'lib/WatchmanLicenseLinter.php',
    'WatchmanLintEngine' => 'lib/WatchmanLintEngine.php',
    'WatchmanPackageWorkflow' => 'workflow/package.php',
    'WatchmanTapEngine' => 'lib/WatchmanTapEngine.php',
    'WatchmanTestCase' => 'lib/WatchmanTestCase.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'WatchmanIntegrationEngine' => 'WatchmanTapEngine',
    'WatchmanLicenseLinter' => 'ArcanistLinter',
    'WatchmanLintEngine' => 'ArcanistLintEngine',
    'WatchmanPackageWorkflow' => 'ArcanistBaseWorkflow',
    'WatchmanTapEngine' => 'ArcanistBaseUnitTestEngine',
    'WatchmanTestCase' => 'ArcanistPhutilTestCase',
  ),
));
