load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("scm_client_infra")

python_library(
    name = "pywatchman_aio",
    srcs = glob(["*.py"]),
    base_module = "pywatchman_aio",
    deps = [
        "//watchman/python/pywatchman:pywatchman",
    ],
)
