load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("scm_client_infra")

cpp_unittest(
    name = "test",
    srcs = ["RootTest.cpp"],
    compatible_with = [
        "ovr_config//os:linux",
        "ovr_config//os:macos",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//folly/portability:gmock",
        "//folly/portability:gtest",
        "//watchman:root",
    ],
)
