load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("scm_client_infra")

cpp_unittest(
    name = "test",
    srcs = ["RootTest.cpp"],
    compatible_with = [
        "ovr_config//os:linux",
        "ovr_config//os:macos",
    ],
    deps = [
        "//folly/portability:gmock",
        "//folly/portability:gtest",
        "//watchman:root",
    ],
)
