load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_buck2_contbuilds")

cpp_library(
    name = "xplat_keys",
    headers = [
        "XplatKeys.h",
    ],
)

cpp_library(
    name = "telemetry",
    srcs = [
        "LogEvent.cpp",
        "WatchmanStats.cpp",
        "WatchmanStructuredLogger.cpp",
    ],
    headers = [
        "LogEvent.h",
        "WatchmanStats.h",
        "WatchmanStructuredLogger.h",
    ],
    deps = [
        "//eden/common/telemetry/facebook:xplat_logger_core",
        "//eden/fs/telemetry:xplat_logger",
        "//watchman:config",
        "//watchman/telemetry:xplat_keys",
        "//watchman/telemetry/facebook:xplat_logger",  # @manual
    ],
    exported_deps = [
        "//eden/common/telemetry:log_info",
        "//eden/common/telemetry:scribe_logger",
        "//eden/common/telemetry:structured_logger",
        "//eden/common/telemetry:structured_logger_factory",
        "//eden/common/telemetry:telemetry",
        "//eden/common/utils:ref_ptr",
        "//folly:stop_watch",
        "//folly:thread_local",
        "//folly/portability:sys_types",
    ],
)
