permalink: /blog/:year/:month/:day/:title.html
title: Watchman
tagline: A file watching service
fbappid: "1615782811974223"
gacode: "UA-44373548-13"
description:
baseurl: "/watchman"
ghrepo: "facebook/watchman"

# Build settings
markdown: redcarpet
highlighter: pygments
lsi: false

exclude: [README.md, publish.sh, Gemfile]
keep_files: [.git, .hg]

collections:
  docs:
    output: true
    permalink: /docs/:name/
  support:
    output: true
    permalink: /support.html

sass:
  style: :compressed

redcarpet:
  extensions: [with_toc_data, no_intra_emphasis, tables, autolink]

color:
  # Provides colour for background of top header of homepage
  primary: "#6779ff"
  # Provides colour for background of elsewhere on site
  secondary: "#e4e4e4"
  # A color that will work for buttons laid on top of primary colour
  light: "#4356e6"
  # Color that will work for text on top of light color
  lighttext: "#fff"
  # Color of text in the top header of homepage, must be legible on top of primary color
  headertext: "#fff"
  # Color of text on top of the secondary color background
  bodytext: "#151515"
  # Background of fixed nav header - headertext color is used for mini logo text
  nav: "#4356e6"
  # Text of links in the nav
  navtext: "#bfc6ff"
  # Color of link underlines in the main body, and hover background color for links
  link: "#4356e6"
