load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("scm_client_infra")

python_unittest(
    name = "tests",
    srcs = glob(["*.py"]),
    compatible_with = [
        "ovr_config//os:linux",
        "ovr_config//os:macos",
    ],
    network_access = network_access_utils.none(),
    supports_static_listing = False,
    deps = [
        "//watchman/python/pywatchman:pywatchman",
    ],
)
