name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-2016]
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: python build/fbcode_builder/getdeps.py build watchman
    - name: Test
      run: python build/fbcode_builder/getdeps.py test watchman
