
name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Fetch boost
      run: python build/fbcode_builder/getdeps.py fetch boost
    - name: Fetch ninja
      run: python build/fbcode_builder/getdeps.py fetch ninja
    - name: Fetch cmake
      run: python build/fbcode_builder/getdeps.py fetch cmake
    - name: Fetch pcre
      run: python build/fbcode_builder/getdeps.py fetch pcre
    - name: Fetch fmt
      run: python build/fbcode_builder/getdeps.py fetch fmt
    - name: Fetch googletest
      run: python build/fbcode_builder/getdeps.py fetch googletest
    - name: Fetch zstd
      run: python build/fbcode_builder/getdeps.py fetch zstd
    - name: Fetch double-conversion
      run: python build/fbcode_builder/getdeps.py fetch double-conversion
    - name: Fetch gflags
      run: python build/fbcode_builder/getdeps.py fetch gflags
    - name: Fetch glog
      run: python build/fbcode_builder/getdeps.py fetch glog
    - name: Fetch libevent
      run: python build/fbcode_builder/getdeps.py fetch libevent
    - name: Fetch snappy
      run: python build/fbcode_builder/getdeps.py fetch snappy
    - name: Fetch folly
      run: python build/fbcode_builder/getdeps.py fetch folly
    - name: Fetch rsocket-cpp
      run: python build/fbcode_builder/getdeps.py fetch rsocket-cpp
    - name: Fetch autoconf
      run: python build/fbcode_builder/getdeps.py fetch autoconf
    - name: Fetch automake
      run: python build/fbcode_builder/getdeps.py fetch automake
    - name: Fetch libtool
      run: python build/fbcode_builder/getdeps.py fetch libtool
    - name: Fetch bison
      run: python build/fbcode_builder/getdeps.py fetch bison
    - name: Fetch libsodium
      run: python build/fbcode_builder/getdeps.py fetch libsodium
    - name: Fetch fizz
      run: python build/fbcode_builder/getdeps.py fetch fizz
    - name: Fetch flex
      run: python build/fbcode_builder/getdeps.py fetch flex
    - name: Fetch wangle
      run: python build/fbcode_builder/getdeps.py fetch wangle
    - name: Fetch fbthrift
      run: python build/fbcode_builder/getdeps.py fetch fbthrift
    - name: Fetch fb303
      run: python build/fbcode_builder/getdeps.py fetch fb303
    - name: Build boost
      run: python build/fbcode_builder/getdeps.py build boost
    - name: Build ninja
      run: python build/fbcode_builder/getdeps.py build ninja
    - name: Build cmake
      run: python build/fbcode_builder/getdeps.py build cmake
    - name: Build pcre
      run: python build/fbcode_builder/getdeps.py build pcre
    - name: Build fmt
      run: python build/fbcode_builder/getdeps.py build fmt
    - name: Build googletest
      run: python build/fbcode_builder/getdeps.py build googletest
    - name: Build zstd
      run: python build/fbcode_builder/getdeps.py build zstd
    - name: Build double-conversion
      run: python build/fbcode_builder/getdeps.py build double-conversion
    - name: Build gflags
      run: python build/fbcode_builder/getdeps.py build gflags
    - name: Build glog
      run: python build/fbcode_builder/getdeps.py build glog
    - name: Build libevent
      run: python build/fbcode_builder/getdeps.py build libevent
    - name: Build snappy
      run: python build/fbcode_builder/getdeps.py build snappy
    - name: Build folly
      run: python build/fbcode_builder/getdeps.py build folly
    - name: Build rsocket-cpp
      run: python build/fbcode_builder/getdeps.py build rsocket-cpp
    - name: Build autoconf
      run: python build/fbcode_builder/getdeps.py build autoconf
    - name: Build automake
      run: python build/fbcode_builder/getdeps.py build automake
    - name: Build libtool
      run: python build/fbcode_builder/getdeps.py build libtool
    - name: Build bison
      run: python build/fbcode_builder/getdeps.py build bison
    - name: Build libsodium
      run: python build/fbcode_builder/getdeps.py build libsodium
    - name: Build fizz
      run: python build/fbcode_builder/getdeps.py build fizz
    - name: Build flex
      run: python build/fbcode_builder/getdeps.py build flex
    - name: Build wangle
      run: python build/fbcode_builder/getdeps.py build wangle
    - name: Build fbthrift
      run: python build/fbcode_builder/getdeps.py build fbthrift
    - name: Build fb303
      run: python build/fbcode_builder/getdeps.py build fb303
    - name: Build watchman
      run: python build/fbcode_builder/getdeps.py build --src-dir=. watchman
    - name: Test watchman
      run: python build/fbcode_builder/getdeps.py test --src-dir=. watchman
  mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Fetch boost
      run: python build/fbcode_builder/getdeps.py fetch boost
    - name: Fetch openssl
      run: python build/fbcode_builder/getdeps.py fetch openssl
    - name: Fetch ninja
      run: python build/fbcode_builder/getdeps.py fetch ninja
    - name: Fetch cmake
      run: python build/fbcode_builder/getdeps.py fetch cmake
    - name: Fetch pcre
      run: python build/fbcode_builder/getdeps.py fetch pcre
    - name: Fetch fmt
      run: python build/fbcode_builder/getdeps.py fetch fmt
    - name: Fetch googletest
      run: python build/fbcode_builder/getdeps.py fetch googletest
    - name: Fetch zstd
      run: python build/fbcode_builder/getdeps.py fetch zstd
    - name: Fetch double-conversion
      run: python build/fbcode_builder/getdeps.py fetch double-conversion
    - name: Fetch gflags
      run: python build/fbcode_builder/getdeps.py fetch gflags
    - name: Fetch glog
      run: python build/fbcode_builder/getdeps.py fetch glog
    - name: Fetch libevent
      run: python build/fbcode_builder/getdeps.py fetch libevent
    - name: Fetch snappy
      run: python build/fbcode_builder/getdeps.py fetch snappy
    - name: Fetch folly
      run: python build/fbcode_builder/getdeps.py fetch folly
    - name: Fetch rsocket-cpp
      run: python build/fbcode_builder/getdeps.py fetch rsocket-cpp
    - name: Fetch autoconf
      run: python build/fbcode_builder/getdeps.py fetch autoconf
    - name: Fetch automake
      run: python build/fbcode_builder/getdeps.py fetch automake
    - name: Fetch libtool
      run: python build/fbcode_builder/getdeps.py fetch libtool
    - name: Fetch bison
      run: python build/fbcode_builder/getdeps.py fetch bison
    - name: Fetch libsodium
      run: python build/fbcode_builder/getdeps.py fetch libsodium
    - name: Fetch fizz
      run: python build/fbcode_builder/getdeps.py fetch fizz
    - name: Fetch flex
      run: python build/fbcode_builder/getdeps.py fetch flex
    - name: Fetch wangle
      run: python build/fbcode_builder/getdeps.py fetch wangle
    - name: Fetch fbthrift
      run: python build/fbcode_builder/getdeps.py fetch fbthrift
    - name: Fetch fb303
      run: python build/fbcode_builder/getdeps.py fetch fb303
    - name: Build boost
      run: python build/fbcode_builder/getdeps.py build boost
    - name: Build openssl
      run: python build/fbcode_builder/getdeps.py build openssl
    - name: Build ninja
      run: python build/fbcode_builder/getdeps.py build ninja
    - name: Build cmake
      run: python build/fbcode_builder/getdeps.py build cmake
    - name: Build pcre
      run: python build/fbcode_builder/getdeps.py build pcre
    - name: Build fmt
      run: python build/fbcode_builder/getdeps.py build fmt
    - name: Build googletest
      run: python build/fbcode_builder/getdeps.py build googletest
    - name: Build zstd
      run: python build/fbcode_builder/getdeps.py build zstd
    - name: Build double-conversion
      run: python build/fbcode_builder/getdeps.py build double-conversion
    - name: Build gflags
      run: python build/fbcode_builder/getdeps.py build gflags
    - name: Build glog
      run: python build/fbcode_builder/getdeps.py build glog
    - name: Build libevent
      run: python build/fbcode_builder/getdeps.py build libevent
    - name: Build snappy
      run: python build/fbcode_builder/getdeps.py build snappy
    - name: Build folly
      run: python build/fbcode_builder/getdeps.py build folly
    - name: Build rsocket-cpp
      run: python build/fbcode_builder/getdeps.py build rsocket-cpp
    - name: Build autoconf
      run: python build/fbcode_builder/getdeps.py build autoconf
    - name: Build automake
      run: python build/fbcode_builder/getdeps.py build automake
    - name: Build libtool
      run: python build/fbcode_builder/getdeps.py build libtool
    - name: Build bison
      run: python build/fbcode_builder/getdeps.py build bison
    - name: Build libsodium
      run: python build/fbcode_builder/getdeps.py build libsodium
    - name: Build fizz
      run: python build/fbcode_builder/getdeps.py build fizz
    - name: Build flex
      run: python build/fbcode_builder/getdeps.py build flex
    - name: Build wangle
      run: python build/fbcode_builder/getdeps.py build wangle
    - name: Build fbthrift
      run: python build/fbcode_builder/getdeps.py build fbthrift
    - name: Build fb303
      run: python build/fbcode_builder/getdeps.py build fb303
    - name: Build watchman
      run: python build/fbcode_builder/getdeps.py build --src-dir=. watchman
    - name: Test watchman
      run: python build/fbcode_builder/getdeps.py test --src-dir=. watchman
  windows:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v1
    - name: Fetch boost
      run: python build/fbcode_builder/getdeps.py fetch boost
    - name: Fetch bison
      run: python build/fbcode_builder/getdeps.py fetch bison
    - name: Fetch flex
      run: python build/fbcode_builder/getdeps.py fetch flex
    - name: Fetch libsodium
      run: python build/fbcode_builder/getdeps.py fetch libsodium
    - name: Fetch ninja
      run: python build/fbcode_builder/getdeps.py fetch ninja
    - name: Fetch cmake
      run: python build/fbcode_builder/getdeps.py fetch cmake
    - name: Fetch pcre
      run: python build/fbcode_builder/getdeps.py fetch pcre
    - name: Fetch fmt
      run: python build/fbcode_builder/getdeps.py fetch fmt
    - name: Fetch googletest
      run: python build/fbcode_builder/getdeps.py fetch googletest
    - name: Fetch zstd
      run: python build/fbcode_builder/getdeps.py fetch zstd
    - name: Fetch double-conversion
      run: python build/fbcode_builder/getdeps.py fetch double-conversion
    - name: Fetch gflags
      run: python build/fbcode_builder/getdeps.py fetch gflags
    - name: Fetch glog
      run: python build/fbcode_builder/getdeps.py fetch glog
    - name: Fetch snappy
      run: python build/fbcode_builder/getdeps.py fetch snappy
    - name: Fetch zlib
      run: python build/fbcode_builder/getdeps.py fetch zlib
    - name: Fetch perl
      run: python build/fbcode_builder/getdeps.py fetch perl
    - name: Fetch openssl
      run: python build/fbcode_builder/getdeps.py fetch openssl
    - name: Fetch libevent
      run: python build/fbcode_builder/getdeps.py fetch libevent
    - name: Fetch folly
      run: python build/fbcode_builder/getdeps.py fetch folly
    - name: Fetch fizz
      run: python build/fbcode_builder/getdeps.py fetch fizz
    - name: Fetch rsocket-cpp
      run: python build/fbcode_builder/getdeps.py fetch rsocket-cpp
    - name: Fetch wangle
      run: python build/fbcode_builder/getdeps.py fetch wangle
    - name: Fetch fbthrift
      run: python build/fbcode_builder/getdeps.py fetch fbthrift
    - name: Fetch fb303
      run: python build/fbcode_builder/getdeps.py fetch fb303
    - name: Build boost
      run: python build/fbcode_builder/getdeps.py build boost
    - name: Build bison
      run: python build/fbcode_builder/getdeps.py build bison
    - name: Build flex
      run: python build/fbcode_builder/getdeps.py build flex
    - name: Build libsodium
      run: python build/fbcode_builder/getdeps.py build libsodium
    - name: Build ninja
      run: python build/fbcode_builder/getdeps.py build ninja
    - name: Build cmake
      run: python build/fbcode_builder/getdeps.py build cmake
    - name: Build pcre
      run: python build/fbcode_builder/getdeps.py build pcre
    - name: Build fmt
      run: python build/fbcode_builder/getdeps.py build fmt
    - name: Build googletest
      run: python build/fbcode_builder/getdeps.py build googletest
    - name: Build zstd
      run: python build/fbcode_builder/getdeps.py build zstd
    - name: Build double-conversion
      run: python build/fbcode_builder/getdeps.py build double-conversion
    - name: Build gflags
      run: python build/fbcode_builder/getdeps.py build gflags
    - name: Build glog
      run: python build/fbcode_builder/getdeps.py build glog
    - name: Build snappy
      run: python build/fbcode_builder/getdeps.py build snappy
    - name: Build zlib
      run: python build/fbcode_builder/getdeps.py build zlib
    - name: Build perl
      run: python build/fbcode_builder/getdeps.py build perl
    - name: Build openssl
      run: python build/fbcode_builder/getdeps.py build openssl
    - name: Build libevent
      run: python build/fbcode_builder/getdeps.py build libevent
    - name: Build folly
      run: python build/fbcode_builder/getdeps.py build folly
    - name: Build fizz
      run: python build/fbcode_builder/getdeps.py build fizz
    - name: Build rsocket-cpp
      run: python build/fbcode_builder/getdeps.py build rsocket-cpp
    - name: Build wangle
      run: python build/fbcode_builder/getdeps.py build wangle
    - name: Build fbthrift
      run: python build/fbcode_builder/getdeps.py build fbthrift
    - name: Build fb303
      run: python build/fbcode_builder/getdeps.py build fb303
    - name: Build watchman
      run: python build/fbcode_builder/getdeps.py build --src-dir=. watchman
    - name: Test watchman
      run: python build/fbcode_builder/getdeps.py test --src-dir=. watchman
